# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Contributors to Eclipse OpenSOVD (see CONTRIBUTORS)
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0

name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  format_and_clippy_nightly_toolchain_pinned:
    concurrency:
      group: format_and_clippy_nightly_toolchain_pinned-${{ github.ref }}
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: false
      - name: Format and Clippy
        uses: eclipse-opensovd/cicd-workflows/rust-lint-and-format-action@3c3da34839e9692d5ca4db226c28926809d9ad6e
        with:
          toolchain: nightly-2025-07-14
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fail-on-format-error: 'true'
          fail-on-clippy-error: 'true'
          clippy-deny-warnings: 'true'

  format_and_clippy_nightly_toolchain_latest:
    needs: format_and_clippy_nightly_toolchain_pinned
    concurrency:
      group: format_and_clippy_nightly_toolchain_latest-${{ github.ref }}
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: false
      - name: Format and Clippy
        uses: eclipse-opensovd/cicd-workflows/rust-lint-and-format-action@3c3da34839e9692d5ca4db226c28926809d9ad6e
        with:
          toolchain: nightly
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fail-on-format-error: 'false'
          fail-on-clippy-error: 'false'
          clippy-deny-warnings: 'false'

  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: false
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.88.0
          components: clippy, rustfmt
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
      - name: Install cargo-deny
        run: cargo install --locked --version 0.18.9 cargo-deny
      - name: Install taplo toml toolkit
        run: cargo install --locked --version 0.10.0 taplo-cli
      - name: check fmt
        run: cargo fmt --all -- --check
      - name: check toml fmt
        run: taplo fmt --check --diff
      - name: Run Clippy
        run: cargo clippy --locked --all-targets -- -D warnings
      - name: Build
        run: cargo build --locked --verbose
      - name: Check licenses
        run: cargo deny check licenses
      - name: Check advisories
        run: cargo deny check advisories
      - name: Check allowed sources
        run: cargo deny check sources
      - name: Check banned practises
        run: cargo deny check bans
      - name: Run tests
        run: cargo test --locked -- --show-output

  build_windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: false
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.88.0
          components: clippy, rustfmt
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --locked --verbose
      - name: Test
        run: cargo test --locked -- --show-output
